name: 'Release on NPM'

on:
  push:
    tags:
      - '*.*.*'

jobs:
  pre-release:
    name: 'Release on NPM'
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        id: setup-node
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 18
          cache: 'npm'
      - name: Install
        run: |
          npm ci
      - name: Build Succeeds
        run: |
          npm run build
      - name: Format Check
        run: |
          npm run lint
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: npm publish --access public
